# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  script: echo "NO TEST SCRIPT WAS PROVIDED" && exit 1
  name: 'android_e2e_tests'
  vmImage: 'macOS-10.15'
  MOCHA_FILE: 'sdk-$(ANDROID_SDK_VERSION)-test-results.xml'
  NODE_VERSION: 10.x
  PLATFORM_VERSION: 9.0

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      CI: true
      TERM: dumb
      ANDROID_AVD: testemulator
      MOCHA_FILE: ${{ parameters.MOCHA_FILE }}
      ANDROID_SDK_VERSION: ${{ parameters.ANDROID_SDK_VERSION }}
      PLATFORM_VERSION: ${{ parameters.PLATFORM_VERSION }}
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.NODE_VERSION }}
    - script: npm install
      displayName: Install Node dependencies
    - script: adb logcat > logcat.txt &
      displayName: Capture Logcat
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: npm run build
      displayName: Build
    - script: ${{ parameters.script }}
      displayName: Run tests
    - task: PublishTestResults@2
      condition: always()
      displayName: Publish Test Results
      inputs:
        testResultsFiles: ${{ parameters.MOCHA_FILE }}
    - task: PublishPipelineArtifact@0
      condition: always()
      displayName: Publish Logcat to Artifacts
      inputs:
        artifactName: ${{ parameters.name }}-logcat
        targetPath: logcat.txt
