# https://docs.microsoft.com/azure/devops/pipelines/languages/android
parameters:
  name: 'android_e2e_tests'
  vmImage: 'macOS-11'
  sdkVersion: 28
  platformVersion: 9.0
  emuTag: default

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    variables:
      TERM: dumb
      ANDROID_AVD: testemulator
      MOCHA_FILE: "sdk-${{ parameters.sdkVersion }}-test-results.xml"
      ANDROID_SDK_VERSION: ${{ parameters.sdkVersion }}
      PLATFORM_VERSION: ${{ parameters.platformVersion }}
      EMU_TAG: ${{ parameters.emuTag }}
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
    - script: npm install
      displayName: Install Node dependencies
    - script: bash ci-jobs/scripts/start-emulator.sh
      displayName: Create and run Emulator
    - script: nohup adb logcat > logcat.txt &
      displayName: Capture Logcat
    - script: npm run e2e-test
      env:
        JAVA_HOME: $(JAVA_HOME_11_X64)
        PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
      displayName: Run tests
    - task: PublishPipelineArtifact@0
      condition: always()
      displayName: Publish Logcat to Artifacts
      inputs:
        artifactName: ${{ parameters.name }}-logcat
        targetPath: logcat.txt
