import * as helpers from './helpers';
import * as lodash from './lodash';

export const APKS_EXTENSION = helpers.APKS_EXTENSION;
export const APK_EXTENSION = helpers.APK_EXTENSION;
export const APK_INSTALL_TIMEOUT = helpers.APK_INSTALL_TIMEOUT;
export const DEFAULT_ADB_EXEC_TIMEOUT = helpers.DEFAULT_ADB_EXEC_TIMEOUT;
export const buildInstallArgs = helpers.buildInstallArgs;
export const readPackageManifest = helpers.readPackageManifest;
export const getResourcePath = helpers.getResourcePath;
export const unzipFile = helpers.unzipFile;
export const getSdkRootFromEnv = helpers.getSdkRootFromEnv;
export const requireSdkRoot = helpers.requireSdkRoot;
export const getJavaHome = helpers.getJavaHome;
export const getJavaForOs = helpers.getJavaForOs;

export const memoize = lodash.memoize;
export const isArray = lodash.isArray;
export const isEmpty = lodash.isEmpty;
export const flatten = lodash.flatten;
export const isNull = lodash.isNull;
export const cloneDeep = lodash.cloneDeep;
export const isNil = lodash.isNil;
export const isNumber = lodash.isNumber;
export const toLower = lodash.toLower;
export const last = lodash.last;
export const trim = lodash.trim;
export const isBoolean = lodash.isBoolean;
export const uniq = lodash.uniq;
export const includes = lodash.includes;
export const some = lodash.some;
export const every = lodash.every;
export const find = lodash.find;
export const values = lodash.values;
export const isInteger = lodash.isInteger;
export const isUndefined = lodash.isUndefined;
export const escapeRegExp = lodash.escapeRegExp;
export const truncate = lodash.truncate;
export const difference = lodash.difference;
export const startsWith = lodash.startsWith;
export const clone = lodash.clone;
export const defaults = lodash.defaults;
export const intersectionWith = lodash.intersectionWith;
export const isEqual = lodash.isEqual;
export const trimEnd = lodash.trimEnd;
export const trimStart = lodash.trimStart;
export const keys = lodash.keys;
export const zip = lodash.zip;
export const toPairs = lodash.toPairs;
export const first = lodash.first;
export const has = lodash.has;
export const pick = lodash.pick;
export const defaultsDeep = lodash.defaultsDeep;
export const isNaN = lodash.isNaN;
export const isString = lodash.isString;
export const range = lodash.range;

export type {BuildInstallArgsOptions} from './helpers';
