jobs:
  - job: adbCI
    pool:
      vmImage: macOS-10.13
    variables:
      CI: true
      TERM: dumb
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
    - script: npm install
      displayName: Install Node dependencies
    - script: npm test
      displayName: NPM Test
