# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:
  # TODO: Add Sauce OnDemand and RDC tests here
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk28_e2e_tests
      PLATFORM_VERSION: 9.0
      ANDROID_SDK_VERSION: 28
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk25_e2e_tests
      PLATFORM_VERSION: 7.1
      ANDROID_SDK_VERSION: 25
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk22_e2e_tests
      PLATFORM_VERSION: 5.1
      ANDROID_SDK_VERSION: 22
