# https://docs.microsoft.com/azure/devops/pipelines/languages/android
jobs:
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk30_e2e_tests
      PLATFORM_VERSION: 11.0
      ANDROID_SDK_VERSION: 30
  - template: templates/android-e2e-template.yml
    parameters:
      script: npx mocha --timeout 6000000 --reporter mocha-multi-reporters --reporter-options configFile=./ci-jobs/mocha-config.json --recursive build/test/functional/ -g @skip-ci -i --exit
      name: sdk29_e2e_tests
      PLATFORM_VERSION: 10.0
      ANDROID_SDK_VERSION: 29
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk28_e2e_tests
      PLATFORM_VERSION: 9.0
      ANDROID_SDK_VERSION: 28
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk25_e2e_tests
      PLATFORM_VERSION: 7.1
      ANDROID_SDK_VERSION: 25
  - template: templates/android-e2e-template.yml
    parameters:
      name: sdk22_e2e_tests
      PLATFORM_VERSION: 5.1
      ANDROID_SDK_VERSION: 22
